### ISSUE TITLE
Dynamic Convolution Attention

### ISSUE THREAD

**Issue by v-nhandt21** [BridgetteSong/ExpressiveTacotron#1]
I found an implement for dynamic convolution attention here, could you consider to add it for your framework.

https://github.com/anandaswarup/TTS/blob/master/tts/layers/attention.py

**Comment by BridgetteSong** [comment]
In my early experiment, DCA is worse than Forward Attention. Maybe there are some problems in my implement, so I don't update DCA in my framework. In fact, Forward Attention is stable enough in many scenes.
